export const dummyPosts = [
  {
    id: 1,
    user: {
      profilePic: "/assets/images/post-profile.png",
      name: "Shay Jordon",
      postTime: "7 hrs ago",
      link: "shay-jordon",
    },
    image: "/assets/images/post-image.jpg",
    heading: "The communal hate propaganda is getting out of hand.",
    subHeading:
      " 3Our prime minister spreading hate speech in a country which is consitutionally secular",
    desc: "I guess most of us here has already heard the speech that our pm gave yesterday which literally was a speech he made t...",
    link: "test-link",
  },
  {
    id: 2,
    user: {
      profilePic: "/assets/images/post-profile.png",
      name: "Shay Jordon1",
      postTime: "8 hrs ago",
      link: "shay-jordon",
    },
    image: "/assets/images/post-image1.jpg",
    heading: "The communal hate propaganda is getting out of hand.1",
    subHeading:
      " 2Our prime minister spreading hate speech in a country which is consitutionally secular",
    desc: "I guess most of us here has already heard the speech that our pm gave yesterday which literally was a speech he made t...",
    link: "test-link",
  },
  {
    id: 3,
    user: {
      profilePic: "/assets/images/post-profile.png",
      name: "Shay Jordon2",
      postTime: "9 hrs ago",
      link: "shay-jordon",
    },
    image: "/assets/images/post-image1.jpg",
    heading: "The communal hate propaganda is getting out of hand.2",
    subHeading:
      " 1Our prime minister spreading hate speech in a country which is consitutionally secular",
    desc: "I guess most of us here has already heard the speech that our pm gave yesterday which literally was a speech he made t...",
    link: "test-link",
  },
];
export const followData = [
  {
    id: 1,
    images: "/assets/images/post-profile.png",
    name: "Phillip George",
    subTitle: "For photos that are, you know, mildl",
    desc: "Aww, cripes. I didn't know I'd have to write a description.",
    followers: 100,
    followings: 200,
    posts: 20,
  },
  {
    id: 2,
    images: "/assets/images/post-profile.png",
    name: "Phillip George",
    subTitle: "For photos that are, you know, mildl",
    desc: "Aww, cripes. I didn't know I'd have to write a description.",
    followers: 100,
    followings: 200,
    posts: 20,
  },
  {
    id: 3,
    images: "/assets/images/post-profile.png",
    name: "Phillip George",
    subTitle: "For photos that are, you know, mildl",
    desc: "Aww, cripes. I didn't know I'd have to write a description.",
    followers: 100,
    followings: 200,
    posts: 20,
  },
  {
    id: 4,
    images: "/assets/images/post-profile.png",
    name: "Phillip George",
    subTitle: "For photos that are, you know, mildl",
    desc: "Aww, cripes. I didn't know I'd have to write a description.",
    followers: 100,
    followings: 200,
    posts: 20,
  },
  {
    id: 5,
    images: "/assets/images/post-profile.png",
    name: "Phillip George",
    subTitle: "For photos that are, you know, mildl",
    desc: "Aww, cripes. I didn't know I'd have to write a description.",
    followers: 100,
    followings: 200,
    posts: 20,
  },
];
