import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import { getSession } from "@/lib";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

config.autoAddCss = false;
// export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "Moji AI",
  description: "Generated by Moji Ai",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8407681477813774"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <AuthSessionProvider session={session}>
        <body className={inter.className}>{children}</body>
      </AuthSessionProvider>
    </html>
  );
}
